# Site settings
title: Kevin VanderLugt
email: kevin.vanderlugt@gmail.com
description: "Portfolio and general chats about my iOS and WatchKit development. Currently working on learning swift, come join the journey!"
baseurl: "http://kevinvanderlugt.com"
url: "http://kevinvanderlugt.com"

# Build settings
markdown: kramdown
permalink: /:title

sass:
    sass_dir: css/_sass
    style: :compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - .gitignore
